# Database Configuration (H2 for local testing)
spring.datasource.url=jdbc:h2:mem:nugar;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# URLs for Dev
app.frontend.url=${APP_FRONTEND_URL:http://192.168.100.15:8081}
app.backend.url=${APP_BACKEND_URL:http://192.168.100.15:8080}
app.market.url=${APP_MARKET_URL:http://192.168.100.15:8082}

# Mail Configuration (Dev)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nugarplus@gmail.com
spring.mail.password=qfsi vyfd nfba cuwm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=noreply@nugar.com
