# Database Configuration (PostgreSQL for Stress Tests)
spring.datasource.url=jdbc:postgresql://localhost:5432/nugar
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# URLs for Test Environment
app.frontend.url=http://192.168.100.15:8081
app.backend.url=http://192.168.100.15:8080

# Mail Configuration (Real Gmail for manual testing in Postgres)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nugarplus@gmail.com
spring.mail.password=qfsi vyfd nfba cuwm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=noreply@nugar.com
